name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: planning

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Unit Test
        run: mvn -B test --file pom.xml

      - name: Build
        run: mvn -B clean package --file pom.xml

      - name: Build docker image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-github-actions:$(date-'%Y-%m-%d%H-%S')
      - name: login to docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Push to Docker hub
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/spring-github-actions:$(date-'%Y-%m-%d%H-%S')